name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      dotnet-logging:
        required: true
        type: choice
        default: minimal
        options:
          - quiet
          - minimal
          - normal
          - detailed
          - diagnostic

jobs:
  all:
    name: Build & Tests
    uses: dailydevops/pipelines/.github/workflows/cicd-dotnet.yml@0.11.0
    with:
      disableCodeFormat: true
      disableCodeQL: true
      disableCoverageUpload: true
      dotnet-logging: ${{ inputs.dotnet-logging }}
      solution: ./NetEvolve.EditorConfig.sln
    secrets: inherit
